name: Deploy my Server
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: yny.ocir.io
          username: ${{ secrets.OCI_REGISTRY_USERNAME }}
          password: ${{ secrets.OCI_REGISTRY_PASSWORD }}

      - name: build the Docker image
        run: |-
          docker build \
          --tag "${{ secrets.OCI_REGISTRY_URL }}/hbnation-app:$GITHUB_SHA" \
          .

      - name: push the Docker image
        run: |-
          docker push "${{ secrets.OCI_REGISTRY_URL }}/hbnation-app:$GITHUB_SHA"
  deploy:
    name: Deploy Kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: set Deployment
        run: |-
          sed -i "s|${{ secrets.OCI_REGISTRY_URL }}/hbnation-app:latest|${{ secrets.OCI_REGISTRY_URL }}/hbnation-app:$GITHUB_SHA|" ./deploy/deployment.yaml

      - name: Deploy
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f ./deploy/deployment.yaml
