name: Deploy my Server
on:
  push:
    branches: [main]
jobs:
  build-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create env
        run: |-
          echo "${{ secrets.NOTION_API_KEY }}" >> .env

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: yny.ocir.io
          username: ${{ secrets.OCI_REGISTRY_USERNAME }}
          password: ${{ secrets.OCI_REGISTRY_PASSWORD }}

      - name: build the Docker image
        run: |-
          docker build \
          --tag "${{ secrets.OCI_REGISTRY_URL }}/hbnation-app:$GITHUB_SHA" \
          .

      - name: push the Docker image
        run: |-
          docker push "${{ secrets.OCI_REGISTRY_URL }}/hbnation-app:$GITHUB_SHA"

      - name: set Deployment
        run: |-
          sed -i "s|hbnation-app:latest|${{ secrets.OCI_REGISTRY_URL }}/hbnation-app:$GITHUB_SHA|" ./deploy/deployment.yml

      - name: Deploy
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f ./deploy/deployment.yml
